// <auto-generated />
using ASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.Migrations.PlansDb
{
    [DbContext(typeof(PlansDbContext))]
    [Migration("20250318144101_InitialCreate_PlansDbContext")]
    partial class InitialCreate_PlansDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ASP.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shelter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weapons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
